name: Java CI with Maven - test and package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs: 
    build:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      
      steps: 
        - name: Se placer sur le premier dépôt
          uses: actions/checkout@v4
        - name: Installer Java
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'corretto'
            cache: 'maven'
        - run: mvn -B javadoc::javadoc
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./reports